name: 'netflix'
version: '1.0.0'
config-version: 2

profile: 'netflix'

model-paths: ["models"]

models:
  staging:
    +schema: STAGING
    +materialized: view

  marts:
    +schema: MART
    +materialized: table
