version: 2

models:
  - name: stg_movies
    columns:
      - name: movie_id
        tests:
          - not_null
          - unique

  - name: stg_ratings
    columns:
      - name: user_id
        tests:
          - not_null

      - name: movie_id
        tests:
          - not_null

      - name: rating
        tests:
          - not_null
