version: 2

sources:
  - name: movielens_raw
    database: NETFLIX_DB
    schema: RAW
    tables:
      - name: ratings
        description: "Raw ratings data from MovieLens (20M)"

      - name: movies
        description: "Raw movies metadata"

      - name: tags
        description: "User-generated tags"

      - name: genome_tags
        description: "Genome tag definitions"

      - name: genome_scores
        description: "Genome tag relevance scores"

      - name: links
        description: "IMDB and TMDB external IDs"