name: 'netflix'
version: '1.0.0'
config-version: 2

profile: 'netflix'

model-paths: ["models"]

models:
  netflix:
    staging:
      +schema: "STAGING"
      +materialized: view

    intermediate:
      +schema: "INTERMEDIATE"
      +materialized: table

    marts:
      +schema: "MART"
      +materialized: table
